//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAREERGROUP
    {
        public string CareerGroupID { get; set; }
        public string CareerGroupName { get; set; }
        public string CareerGroupDescription { get; set; }
        public string CareerGroupURL { get; set; }
        public string CareerGroupImageURL { get; set; }
        public string ContentID { get; set; }
        public string CareerGroupNameForURL { get; set; }
    }
}
