//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERNALLINK
    {
        public short LinkOrder { get; set; }
        public string LinkFromType { get; set; }
        public string LinkToType { get; set; }
        public string LinkFromID { get; set; }
        public string LinkToID { get; set; }
    }
}
