//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCEED
    {
        public int ProceedID { get; set; }
        public string VisitorIP { get; set; }
        public string ProceedFromPage { get; set; }
        public string SalaryAddedAttempts { get; set; }
        public string SalaryAdded { get; set; }
        public string ProceedErrors { get; set; }
        public Nullable<System.DateTime> ProceedDate { get; set; }
    }
}
