//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANx
    {
        public string RangeGroupID { get; set; }
        public short RangeID { get; set; }
        public int RangeFrom { get; set; }
        public int RangeTo { get; set; }
        public int RangeAverage { get; set; }
        public string Percentage { get; set; }
    }
}
