//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESTRICTEDBROWSER
    {
        public int ID { get; set; }
        public string BrowserVersion { get; set; }
        public string BrowserSettings { get; set; }
    }
}
