//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALARYANSWER
    {
        public string QuestionID { get; set; }
        public string AnswerID { get; set; }
        public string Answer { get; set; }
        public System.DateTime DatePosted { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UserID { get; set; }
        public string VisitorIP { get; set; }
        public Nullable<bool> IsBrowser { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public string BrowserVersion { get; set; }
        public string BrowserSettings { get; set; }
    }
}
