//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALARYQUESTION
    {
        public string QuestionID { get; set; }
        public string QuestionSubject { get; set; }
        public string Question { get; set; }
        public System.DateTime DateStarted { get; set; }
        public string UserStarted { get; set; }
        public Nullable<System.DateTime> DateLastAnswer { get; set; }
        public Nullable<short> AnswersCount { get; set; }
        public Nullable<int> ViewsCount { get; set; }
        public string UserLastPost { get; set; }
        public string VisitorIP { get; set; }
        public Nullable<bool> IsBrowser { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public string BrowserVersion { get; set; }
        public string BrowserSettings { get; set; }
    }
}
