//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSTutorial.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRy
    {
        public string CountryID { get; set; }
        public string CountryName { get; set; }
        public string Currency { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<long> CountryAverageSalary { get; set; }
        public Nullable<int> CountryAverageSalaryUSD { get; set; }
        public Nullable<decimal> CurrencyRatioToUSD { get; set; }
        public string CountryScale { get; set; }
        public string ConvertToUSD { get; set; }
        public string IsEU { get; set; }
        public string CountryURL { get; set; }
        public string CountryImageURL { get; set; }
        public string ContentID { get; set; }
        public string CountryNameForURL { get; set; }
    }
}
